apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret                      # -- Provide external secret name
  namespace: kube-system                     # -- Do not change this namespace field
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: external-secrets-store             # -- Provide previously created secret store name
    kind: SecretStore
  target:
    name: externalsecret-data                # -- Name of Kubernetes secret which will contain data specified below
    creationPolicy: Owner
  data:
  - secretKey: external_secret_key           # -- Kubernetes Secret `externalsecret-data` KEY name
    remoteRef:
      key: external_secrets_addon            # -- AWS Secret Name, same as `var.external_secrets_extra_configs.secret_manager_name`
      property: external_secret              # -- AWS Secret-Manager secret key