server:    
  ## Node affinity for particular node in which labels key is "Infra-Services" and value is "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "eks.amazonaws.com/nodegroup"
            operator: In
            values:
            - "critical"

  persistentVolume:     # Persistent volume will not be deployed for prometheus server pod - Enable if EBS or EFS CSI Driver is installed
    enabled: false

  resources: 
    limits:
      cpu: 300m
      memory: 250Mi
    requests:
      cpu: 50m
      memory: 150Mi

alertmanager:                 # Dependency for prometheus server
  enabled: true
  persistence:                # Persistent volume will not be deployed for alertmanager - Enable if EBS or EFS CSI Driver is installed
    enabled: false

kube-state-metrics:           # Dependency for prometheus server
  enabled: true

prometheus-node-exporter:     # Dependency for prometheus server
  enabled: true

prometheus-pushgateway:       # Dependency for prometheus server
  enabled: true