global:
  storageClass: ""
  redis:
    password: "redisPassword"

# -- master configuration parameters
master:
  count: 1
  persistence:
    size: 4Gi    

# -- replicas configuration parameters
replica:
  replicaCount: 3
  persistence:
    size: 4Gi