## Node affinity for particular node in which labels key is "Infra-Services" and value is "true"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: "eks.amazonaws.com/nodegroup"
          operator: In
          values:
          - "critical-nodes"

## Using limits and requests
resources:
  limits:
    cpu: 300m
    memory: 250Mi
  requests:
    cpu: 50m
    memory: 150Mi

# Configuration is rendered with `tpl` function, therefore you can use any Helm variables and/or templates here
config: |-
  # This is the default configuration for prometheus-cloudwatch-exporter
  region: us-east-1
  metrics:
  - aws_dimensions:
    - InstanceId
    aws_metric_name: CPUUtilization
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
    aws_tag_select:
      resource_type_selection: ec2:instance
      resource_id_dimension: InstanceId
  - aws_dimensions:
    - InstanceId
    aws_metric_name: NetworkIn
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
  - aws_dimensions:
    - InstanceId
    aws_metric_name: NetworkOut
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
  - aws_dimensions:
    - InstanceId
    aws_metric_name: NetworkPacketsIn
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
  - aws_dimensions:
    - InstanceId
    aws_metric_name: NetworkPacketsOut
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
  - aws_dimensions:
    - InstanceId
    aws_metric_name: DiskWriteBytes
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
  - aws_dimensions:
    - InstanceId
    aws_metric_name: DiskReadBytes
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
  - aws_dimensions:
    - InstanceId
    aws_metric_name: CPUCreditBalance
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
  - aws_dimensions:
    - InstanceId
    aws_metric_name: CPUCreditUsage
    aws_namespace: AWS/EC2
    aws_statistics:
    - Average
  - aws_dimensions:
    - InstanceId
    aws_metric_name: StatusCheckFailed
    aws_namespace: AWS/EC2
    aws_statistics:
    - Sum
  - aws_dimensions:
    - InstanceId
    aws_metric_name: StatusCheckFailed_Instance
    aws_namespace: AWS/EC2
    aws_statistics:
    - Sum
  - aws_dimensions:
    - InstanceId
    aws_metric_name: StatusCheckFailed_System
    aws_namespace: AWS/EC2
    aws_statistics:
    - Sum