apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: kube-system             # -- keep this namespace same as ExternalSecret namespace
  labels:
    app: ubuntu-pod
spec:
  containers:
  - image: ubuntu
    command:
      - "sleep"
      - "604800"
    imagePullPolicy: IfNotPresent
    name: ubuntu-pod
    env:
      - name: USER_1                           # -- Environment variable of pod
        valueFrom:
          secretKeyRef:
            name: externalsecret-data
            key: sm_secret_key_1               # -- Same as spec.data.secretKey[1] field of ExternalStore          
            optional: false
      - name: USER_2                           # -- Environment variable of pod           
        valueFrom:
          secretKeyRef:
            name: externalsecret-data
            key: sm_secret_key_2               # -- Same as spec.data.secretKey[2] field of ExternalStore      
            optional: false    
  restartPolicy: Always