serviceAccounts:
  server:
    create: true

  prometheus:
    enabled: true

    ## config-reloader's container port and port name for probes and metrics
    containerPort: 8080
    containerPortName: metrics

    ## Settings for Prometheus reloader's readiness, liveness and startup probes
    livenessProbe:
      httpGet:
        path: /healthz
        port: metrics
        scheme: HTTP
      periodSeconds: 10
      initialDelaySeconds: 2

    readinessProbe:
      httpGet:
        path: /healthz
        port: metrics
        scheme: HTTP
      periodSeconds: 10

    startupProbe:
      enabled: false
      httpGet:
        path: /healthz
        port: metrics
        scheme: HTTP
      periodSeconds: 10

server:

  name: server      # Prometheus server container name
  clusterRoleNameOverride: "prom-role"

  ## Node affinity for particular node in which labels key is "Infra-Services" and value is "true"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: "eks.amazonaws.com/nodegroup"
                operator: In
                values:
                  - "critical-nodes"

  persistentVolume:
    size: 8Gi       # Prometheus server data Persistent Volume size
    storageClass: "gp2"

  resources:
    limits:
      cpu: 300m
      memory: 250Mi
    requests:
      cpu: 50m
      memory: 150Mi

# serverFiles:
#   prometheus.yml:
#     scrape_configs:
#       This is Scrape config for Prometheus Cloudwatch Exporter service to get scrape
#       Uncomment Below Code to use prometheus Cloudwatch Exporter as a scrape config for prometheus
#       - job_name: cloudwatch-exporter
#         static_configs:
#           - targets:
#             - 'prometheus-cloudwatch-exporter.monitoring.svc.cluster.local:9106'
#             labels:
#               csp: 'aws'
#               cn: '<Compnay name>'
#               account_id: '<AWS Account Number>'


alertmanager:                # Dependency for prometheus server
  persistence:               # Persistent volume will not be deployed for alertmanager - Enable if EBS or EFS CSI Driver is installed
    size: 2Gi
    storageClass: "gp2"

kube-state-metrics:          # Dependency for prometheus server
  enabled: false

