global:
  storageClass: ""
  redis:
    password: "redisPassword"

# -- master configuration parameters
master:
  count: 1
  persistence:
    size: 4Gi    
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "eks.amazonaws.com/nodegroup"
            operator: In
            values:
            - "critical-nodes"    

# -- replicas configuration parameters
replica:
  replicaCount: 3
  persistence:
    size: 4Gi
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "eks.amazonaws.com/nodegroup"
            operator: In
            values:
            - "critical-nodes"    