---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-pod-restart-info-collector.fullname" . }}
  labels:
    {{- include "k8s-pod-restart-info-collector.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-pod-restart-info-collector.fullname" . }}
  labels:
    {{- include "k8s-pod-restart-info-collector.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "pods/log", "events"]
  verbs: ["get", "list", "watch"]
# for GKE PodSecurityPolicy
# - apiGroups: ["extensions"]
#   resourceNames: ["gce.unprivileged-addon"]
#   resources: ["podsecuritypolicies"]
#   verbs: ["use"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-pod-restart-info-collector.fullname" . }}
  labels:
    {{- include "k8s-pod-restart-info-collector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-pod-restart-info-collector.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "k8s-pod-restart-info-collector.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}