apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali
spec:
  hosts:
    - dash.test.clouddrove.com
  gateways:
  - istio-system/istio-gateway
  http:
  - route:
    - destination:
        host: kiali
        port:
          number: 20001