name: terraform workflow
permissions: write-all
on:
  push:
    branches: [ feat/addon_nginx-ingress ]
  # pull_request:
  workflow_dispatch:
jobs:
  prod:
    uses: clouddrove/github-shared-workflows/.github/workflows/terraform_workflow.yml@internal_357
    with:
        provider: aws
        working_directory:  ./_examples/complete
        aws_region: us-east-1
        approvers:  dipak2515
        terraform_version:  1.5.4
        timeout: 10
    secrets:
        BUILD_ROLE: ${{ secrets.BUILD_ROLE }}
